spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.10.96:3306/online_test?useSSL=false&characterEncoding=utf8
        username: root
        password: xlm123456
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ks_xlm.model